# Generated by Django 4.1.1 on 2022-09-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_apply_companyregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregister',
            name='applyhere',
            field=models.URLField(),
        ),
    ]
