# Generated by Django 4.1.1 on 2022-09-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_companyregister_applyhere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('admissionNo', models.CharField(max_length=100)),
                ('uniRegNo', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('tenthaggr', models.CharField(max_length=100)),
                ('twelvethaggr', models.CharField(max_length=100)),
                ('backlogs', models.CharField(max_length=100)),
                ('cgpa', models.CharField(max_length=100)),
                ('registered_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
